baseURL = "https://daniil-aleksieiev.github.io/starter-kit-hugo-with-gulp/"
languageCode = "en-us"
theme = "project_theme"
title = "Hugo with Gulp starter kit"
disableHugoGeneratorInject = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Docs"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pre = "<i class='fa fa-heart'></i>"
    url = "/blog/"
    weight = 2

[params]
  title = "Hugo with Gulp starter kit"
  addURL = "starter-kit-hugo-with-gulp"

[taxonomies]
  category = "category"
