---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: content/blog/_index.md
  label: TEST
  match: "**/*"
- type: directory
  path: data
  label: Data
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/_index.md"
- type: directory
  path: content/blog/posts
  label: Blog
  create: documents
  match: "*"
upload_dir: themes/project_theme/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.55.6
